ideal5: Experiment.d Interaction.d Anticipation.d Existence.d Environment050.d EnvironmentMaze.d Main.d
	dmd Experiment.d Interaction.d Anticipation.d Existence.d Environment050.d EnvironmentMaze.d Main.d -ofideal5
