ideal1: Existence.d Experiment.d Result.d Interaction.d Interaction010.d Interaction020.d Existence010.d Existence020.d Main.d
	dmd Existence.d Experiment.d Result.d Interaction.d Interaction010.d Interaction020.d Existence010.d Existence020.d Main.d -ofideal2
